services:
    api:
        networks:
            - lockr-network
        build:
            target: development
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/usr/src/app
        command: npm run dev

networks:
    lockr-network:
        driver: bridge
