services:
    api:
        container_name: lockr-api
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PORT=${PORT:-3000}
        ports:
            - ${PORT:-3000}:${PORT:-3000}
